POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "mutation createLink($url: String!, $desc: String!){createLink(url: $url, description: $desc) { id, url, description, createdAt } } ",
  "variables": {
    "url": "http://dot.com",
    "desc": "Dot Com"
  }
}

###
